{{- if eq (include "isInternalDatabase" .) "true"  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "odm.dbserver.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "dbserver" "root" .) | indent 4 }}
spec:
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    run: {{ template "odm.dbserver.fullname" . }}
  type: ClusterIP
  ports:
   - protocol: TCP
     port: 5432
{{- end }}
