{{- if and (empty .Values.decisionCenter.webConfigRef) (.Values.decisionCenter.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.dc-web-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionCenter" "root" .) | indent 4 }}
data:
  web-configuration.properties: |
    # Add Web.xml context-param properties below
{{- end }}
