{{- if .Values.decisionRunner.autoscaling }}
{{- if .Values.decisionRunner.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "odm.decisionrunner.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionRunner" "root" .) | indent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "odm.decisionrunner.fullname" . }}
  minReplicas: {{ .Values.decisionRunner.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.decisionRunner.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.decisionRunner.autoscaling.targetAverageUtilization }}
{{- end }}
{{- end }}
