{{- if and .Values.decisionRunner.enabled (and .Values.service.enableRoute  .Values.service.enableTLS) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{  template "odm-dr-route.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionRunner" "root" .) | indent 4 }}
spec:
  {{- if not (empty .Values.service.hostname) }}
  host: decisionrunner.odm.{{ .Release.Name }}.{{ .Values.service.hostname }}
  {{- end }}
  port:
    targetPort: decisionrunner-https
  tls:
    termination: passthrough
  to:
    kind: Service
    name:  {{ template "odm.decisionrunner.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end }}
