{{- if .Values.decisionRunner.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "odm.decisionrunner.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionRunner" "root" .) | indent 4 }}
spec:
  sessionAffinity : ClientIP
  selector:
    app: {{ template "fullname" . }}
    release: {{ .Release.Name }}
    run: {{ template "odm.decisionrunner.fullname" . }}
{{ include "odm-service-type" . | indent 2 }}
  ports:
   - protocol: TCP
     port: 9443
     {{- if .Values.service.enableTLS }}
     name: decisionrunner-https
     targetPort: 9443
     {{ else }}
     name: decisionrunner
     targetPort: 9080
     {{- end }}
{{- end }}
