{{- if and .Values.decisionServerRuntime.enabled (and .Values.service.enableRoute .Values.service.enableTLS) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{  template "odm-ds-runtime-route.fullname" . }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
spec:
  {{- if not (empty .Values.service.hostname) }}
  host: decisionserverruntime.odm.{{ .Release.Name }}.{{ .Values.service.hostname }}
  {{- end }}
  port:
    targetPort: decisionserverruntime-https
  tls:
    termination: passthrough
  to:
    kind: Service
    name:  {{ template "odm.decisionserverruntime.fullname" . }}
    weight: 100
  wildcardPolicy: None

{{- end }}
