{{- if and (empty .Values.decisionServerRuntime.xuConfigRef) (.Values.decisionServerRuntime.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.ds-runtime-xu-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
data:
  xu-configuration.properties: |
    # Add XU properties below
{{- end }}
