{{- if and (empty .Values.decisionServerRuntime.jvmOptionsRef) (.Values.decisionServerRuntime.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.ds-runtime-jvm-options-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
data:
  dsr-jvm-options: |
    -Duser.timezone=Europe/Paris
    -Dcom.ibm.jsse2.overrideDefaultTLS=true
    {{- if .Values.customization.enableFips }}
    -Dsemeru.fips=true
    -Djava.security.properties=/opt/ibm/wlp/usr/servers/defaultServer/jvm/enablefips-java.security
    {{- end }}
{{- end }}
