{{- if and (empty .Values.decisionServerRuntime.webConfigRef) (or .Values.decisionRunner.enabled .Values.decisionServerRuntime.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ template "odm.ds-runtime-web-configmap.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "decisionServerRuntime" "root" .) | indent 4 }}
data:
  web-configuration.properties: |
    # Add Web.xml context-param properties below
{{- end }}
