{{- if and ( .Values.oidc.enabled) (empty .Values.customization.authSecretRef) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odm.oidc-auth-secret.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "oidc" "root" .) | indent 4 }}
type: Opaque
stringData:
  webSecurity.xml: |-
{{ .Files.Get "oidc/webSecurity.xml"}}
{{- end }}
