{{- if and (empty  .Values.externalDatabase.decisionCenter.secretCredentials) (and (empty .Values.externalDatabase.decisionServer.secretCredentials) (and (empty .Values.customization.vault) (and (empty .Values.externalDatabase.secretCredentials) (empty .Values.internalDatabase.secretCredentials)))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "odm.secret.fullname" . }}
  labels:
{{ include "odm-additional-labels" (dict "componentName" "odm" "root" .) | indent 4 }}
type: Opaque
data:
  {{- if eq (include "isExternalDatabase" .) "false" }}
  db-user: {{ .Values.internalDatabase.user | b64enc | quote }}
  {{- if .Values.internalDatabase.password }}
  db-password:  {{ .Values.internalDatabase.password | b64enc | quote }}
  {{- else }}
  db-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- else }}
  db-user: {{ (include "odm-external-sec-user" .)  | b64enc | quote }}
  db-password:  {{ (include "odm-external-sec-password" .)  | b64enc | quote }}
  {{- end }}
{{- end }}
