{{- if empty .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-service-account
  labels:
{{ include "odm-additional-labels" (dict "componentName" "odm" "root" .) | indent 4 }}
automountServiceAccountToken: false
imagePullSecrets:
  - name: sa-{{ .Release.Namespace }}
{{- end }}
